#!/bin/bash

HOST=$1

rsync p1_to_mqtt.py root@$HOST:~/
rsync config.json root@$HOST:~/
rsync p1-to-mqtt.service root@$HOST:/etc/systemd/system/

ssh -n root@$HOST 'chmod 644 /etc/systemd/system/p1-to-mqtt.service'
ssh -n root@$HOST 'systemctl daemon-reload'
ssh -n root@$HOST 'systemctl enable p1-to-mqtt.service'
ssh -n root@$HOST 'systemctl restart p1-to-mqtt'
