#!/bin/bash

REMOTE_USER=$1
REMOTE_HOST=$2
REMOTE_DIST=$3
MQTT_HOST=$4
MQTT_USERNAME=$5
MQTT_PASSWORD=$6

echo "Deploy to $REMOTE_HOST with REMOTE_DIST $REMOTE_DIST and MQTT $MQTT_USERNAME@$MQTT_HOST"

[ -z "$REMOTE_USER" ] && { echo "REMOTE_USER argument is missing"; exit 1; }
[ -z "$REMOTE_HOST" ] && { echo "REMOTE_HOST argument is missing"; exit 1; }
[ -z "$REMOTE_DIST" ] && { echo "REMOTE_DIST argument is missing"; exit 1; }
[ -z "$MQTT_HOST" ] && { echo "MQTT_HOST argument is missing"; exit 1; }
[ -z "$MQTT_USERNAME" ] && { echo "MQTT_USERNAME argument is missing"; exit 1; }
[ -z "$MQTT_PASSWORD" ] && { echo "MQTT_PASSWORD argument is missing"; exit 1; }


rsync install/$REMOTE_DIST/* root@$REMOTE_HOST:~/
ssh -n $REMOTE_USER@$REMOTE_HOST './pre-install'

cp config_example.json config.json
sed -i.bak "s/<MQTT_HOST>/$MQTT_HOST/" config.json
sed -i.bak "s/<MQTT_USERNAME>/$MQTT_USERNAME/" config.json
sed -i.bak "s/<MQTT_PASSWORD>/$MQTT_PASSWORD/" config.json

rsync -a p1_to_mqtt root@$REMOTE_HOST:~/
rsync config.json root@$REMOTE_HOST:~/
rsync files/etc/systemd/system/p1-to-mqtt.service root@$REMOTE_HOST:/etc/systemd/system/

ssh -n root@$REMOTE_HOST './post-install'
